"""
Exploratory Data Analysis engine.

Computes a wide battery of REAL aggregations, cross-tabs, and statistical
tests against the Phase 2 processed dataset. Every number in the Phase 3
insights report is generated by this script — nothing is hand-typed or
estimated. Run this file to regenerate insights_data.json from scratch.
"""

import os
import sys
import json
import numpy as np
import pandas as pd
from scipy import stats

sys.path.append(os.path.join(os.path.dirname(__file__), "..", ".."))
from src.utils.logger import get_logger

logger = get_logger(__name__)

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DATA_PATH = os.path.join(PROJECT_ROOT, "data", "processed", "customer_churn_processed.csv")
OUTPUT_JSON = os.path.join(PROJECT_ROOT, "docs", "insights_data.json")


def load_data() -> pd.DataFrame:
    df = pd.read_csv(DATA_PATH)
    df["tenure_cohort"] = pd.Categorical(
        df["tenure_cohort"],
        categories=["0-12 mo", "13-24 mo", "25-36 mo", "37-48 mo", "49-60 mo", "61-72 mo"],
        ordered=True,
    )
    return df


def pct(x, n):
    return round(100 * x / n, 2) if n else None


def overview_metrics(df):
    n = len(df)
    churned = df["churn_flag"].sum()
    return {
        "total_customers": int(n),
        "churned_customers": int(churned),
        "retained_customers": int(n - churned),
        "overall_churn_rate_pct": pct(churned, n),
        "total_billed_revenue": round(df["total_charges"].sum(), 2),
        "monthly_recurring_revenue": round(df["monthly_charges"].sum(), 2),
        "avg_monthly_charges": round(df["monthly_charges"].mean(), 2),
        "avg_tenure_months": round(df["tenure_months"].mean(), 2),
        "median_tenure_months": round(df["tenure_months"].median(), 2),
        "avg_cltv": round(df["cltv"].mean(), 2),
        "avg_cltv_churned": round(df.loc[df.churn_flag == 1, "cltv"].mean(), 2),
        "avg_cltv_retained": round(df.loc[df.churn_flag == 0, "cltv"].mean(), 2),
        "revenue_at_risk_from_churned_monthly": round(df.loc[df.churn_flag == 1, "monthly_charges"].sum(), 2),
    }


def churn_by_categorical(df, col):
    g = df.groupby(col, observed=True).agg(
        customers=("customer_id", "count"),
        churned=("churn_flag", "sum"),
        avg_monthly_charges=("monthly_charges", "mean"),
        avg_tenure=("tenure_months", "mean"),
        avg_cltv=("cltv", "mean"),
        total_revenue=("total_charges", "sum"),
    ).reset_index()
    g["churn_rate_pct"] = (g["churned"] / g["customers"] * 100).round(2)
    g["avg_monthly_charges"] = g["avg_monthly_charges"].round(2)
    g["avg_tenure"] = g["avg_tenure"].round(2)
    g["avg_cltv"] = g["avg_cltv"].round(2)
    g["total_revenue"] = g["total_revenue"].round(2)
    return g.sort_values("churn_rate_pct", ascending=False).to_dict(orient="records")


def chi_square_test(df, col):
    ct = pd.crosstab(df[col], df["churn_label"])
    chi2, p, dof, _ = stats.chi2_contingency(ct)
    return {"variable": col, "chi2": round(chi2, 3), "p_value": round(p, 6), "significant_at_05": bool(p < 0.05)}


def ttest_numeric(df, col):
    churned = df.loc[df.churn_flag == 1, col].dropna()
    retained = df.loc[df.churn_flag == 0, col].dropna()
    t, p = stats.ttest_ind(churned, retained, equal_var=False)
    return {
        "variable": col,
        "mean_churned": round(churned.mean(), 2),
        "mean_retained": round(retained.mean(), 2),
        "t_stat": round(t, 3),
        "p_value": round(p, 6),
        "significant_at_05": bool(p < 0.05),
    }


def top_cities(df, n=10):
    g = df.groupby("city").agg(
        customers=("customer_id", "count"),
        churned=("churn_flag", "sum"),
        total_revenue=("total_charges", "sum"),
    ).reset_index()
    g = g[g["customers"] >= 5]  # avoid noisy single-customer "cities"
    g["churn_rate_pct"] = (g["churned"] / g["customers"] * 100).round(2)
    g["total_revenue"] = g["total_revenue"].round(2)
    by_revenue = g.sort_values("total_revenue", ascending=False).head(n).to_dict(orient="records")
    by_churn = g.sort_values("churn_rate_pct", ascending=False).head(n).to_dict(orient="records")
    return {"top_by_revenue": by_revenue, "top_by_churn_rate_min5cust": by_churn}


def addon_analysis(df):
    g = df.groupby("addon_service_count").agg(
        customers=("customer_id", "count"),
        churned=("churn_flag", "sum"),
        avg_monthly_charges=("monthly_charges", "mean"),
    ).reset_index()
    g["churn_rate_pct"] = (g["churned"] / g["customers"] * 100).round(2)
    g["avg_monthly_charges"] = g["avg_monthly_charges"].round(2)
    return g.to_dict(orient="records")


def churn_reason_breakdown(df):
    churned = df[df.churn_flag == 1]
    g = churned.groupby("churn_reason").agg(
        customers=("customer_id", "count"),
        avg_monthly_charges=("monthly_charges", "mean"),
        avg_tenure=("tenure_months", "mean"),
        lost_monthly_revenue=("monthly_charges", "sum"),
    ).reset_index()
    total_churned = len(churned)
    g["pct_of_churn"] = (g["customers"] / total_churned * 100).round(2)
    g["avg_monthly_charges"] = g["avg_monthly_charges"].round(2)
    g["avg_tenure"] = g["avg_tenure"].round(2)
    g["lost_monthly_revenue"] = g["lost_monthly_revenue"].round(2)
    return g.sort_values("customers", ascending=False).to_dict(orient="records")


def churn_score_decile_analysis(df):
    df = df.copy()
    df["churn_score_decile"] = pd.qcut(df["churn_score"], 10, labels=False, duplicates="drop") + 1
    g = df.groupby("churn_score_decile").agg(
        customers=("customer_id", "count"),
        actual_churned=("churn_flag", "sum"),
        avg_churn_score=("churn_score", "mean"),
        avg_cltv=("cltv", "mean"),
        total_monthly_revenue=("monthly_charges", "sum"),
    ).reset_index()
    g["actual_churn_rate_pct"] = (g["actual_churned"] / g["customers"] * 100).round(2)
    g["avg_churn_score"] = g["avg_churn_score"].round(1)
    g["avg_cltv"] = g["avg_cltv"].round(2)
    g["total_monthly_revenue"] = g["total_monthly_revenue"].round(2)
    return g.sort_values("churn_score_decile", ascending=False).to_dict(orient="records")


def payment_method_analysis(df):
    return churn_by_categorical(df, "payment_method")


def tenure_cohort_analysis(df):
    return churn_by_categorical(df, "tenure_cohort")


def contract_analysis(df):
    return churn_by_categorical(df, "contract_type")


def internet_service_analysis(df):
    return churn_by_categorical(df, "internet_service")


def demographic_analysis(df):
    return {
        "gender": churn_by_categorical(df, "gender"),
        "senior_citizen": churn_by_categorical(df, "senior_citizen"),
        "has_partner": churn_by_categorical(df, "has_partner"),
        "has_dependents": churn_by_categorical(df, "has_dependents"),
    }


def correlation_matrix(df):
    numeric_cols = [
        "tenure_months", "monthly_charges", "total_charges", "churn_score",
        "cltv", "addon_service_count", "avg_revenue_per_tenure_month", "churn_flag",
    ]
    corr = df[numeric_cols].corr(numeric_only=True).round(3)
    return corr.to_dict()


def funnel_style_service_adoption(df):
    """
    Not a true acquisition funnel (no session/signup event stream in this
    dataset) — this is a service-adoption funnel: base connectivity -> add-on
    adoption -> full bundle, using real service flags only.
    """
    n = len(df)
    has_phone = (df["phone_service_bool"]).sum()
    has_internet = (df["has_internet"]).sum()
    has_both = (df["has_phone_and_internet"]).sum()
    has_1plus_addon = (df["addon_service_count"] >= 1).sum()
    has_3plus_addon = (df["addon_service_count"] >= 3).sum()
    full_bundle = (df["addon_service_count"] == 6).sum()
    return {
        "total_customers": int(n),
        "has_phone_service": {"count": int(has_phone), "pct": pct(has_phone, n)},
        "has_internet_service": {"count": int(has_internet), "pct": pct(has_internet, n)},
        "has_phone_and_internet": {"count": int(has_both), "pct": pct(has_both, n)},
        "has_1plus_addon_services": {"count": int(has_1plus_addon), "pct": pct(has_1plus_addon, n)},
        "has_3plus_addon_services": {"count": int(has_3plus_addon), "pct": pct(has_3plus_addon, n)},
        "full_addon_bundle_all6": {"count": int(full_bundle), "pct": pct(full_bundle, n)},
    }


def revenue_concentration(df):
    """What share of total revenue comes from top X% of customers by CLTV?"""
    sorted_df = df.sort_values("cltv", ascending=False).reset_index(drop=True)
    n = len(sorted_df)
    total_rev = sorted_df["total_charges"].sum()
    results = {}
    for top_pct in [10, 20, 50]:
        cutoff = int(n * top_pct / 100)
        rev_share = sorted_df.loc[:cutoff, "total_charges"].sum()
        results[f"top_{top_pct}pct_by_cltv_revenue_share_pct"] = round(100 * rev_share / total_rev, 2)
    return results


def run_full_eda():
    logger.info("Loading processed data for EDA...")
    df = load_data()

    logger.info("Computing overview metrics...")
    overview = overview_metrics(df)

    logger.info("Running statistical tests...")
    categorical_tests = [
        chi_square_test(df, col) for col in
        ["contract_type", "internet_service", "payment_method", "gender",
         "senior_citizen", "has_partner", "has_dependents", "paperless_billing",
         "tenure_cohort", "multiple_lines", "online_security", "tech_support",
         "streaming_tv", "streaming_movies"]
    ]
    numeric_tests = [
        ttest_numeric(df, col) for col in
        ["tenure_months", "monthly_charges", "total_charges", "churn_score",
         "cltv", "addon_service_count", "avg_revenue_per_tenure_month"]
    ]

    results = {
        "overview": overview,
        "contract_analysis": contract_analysis(df),
        "internet_service_analysis": internet_service_analysis(df),
        "payment_method_analysis": payment_method_analysis(df),
        "tenure_cohort_analysis": tenure_cohort_analysis(df),
        "demographic_analysis": demographic_analysis(df),
        "addon_analysis": addon_analysis(df),
        "churn_reason_breakdown": churn_reason_breakdown(df),
        "churn_score_decile_analysis": churn_score_decile_analysis(df),
        "top_cities": top_cities(df),
        "correlation_matrix": correlation_matrix(df),
        "service_adoption_funnel": funnel_style_service_adoption(df),
        "revenue_concentration": revenue_concentration(df),
        "statistical_tests": {
            "chi_square_categorical_vs_churn": categorical_tests,
            "ttest_numeric_vs_churn": numeric_tests,
        },
    }

    os.makedirs(os.path.dirname(OUTPUT_JSON), exist_ok=True)
    with open(OUTPUT_JSON, "w") as f:
        json.dump(results, f, indent=2, default=str)
    logger.info(f"EDA results written to {OUTPUT_JSON}")
    return results


if __name__ == "__main__":
    run_full_eda()
